### ISSUE TITLE
TypeError: block is undefined @ id3/bufferedbinaryajax.js:215

### ISSUE THREAD

**Issue by veka-server** [aadsm/JavaScript-ID3-Reader#24]
I found this bug with one on my mp3.

i debug like this : 

BEFORE :

``` javascript
this.getByteAt = function(iOffset) {
    var block = getBlockAtOffset(iOffset);
    if( typeof block.data == "string" ) {
```

AFTER :

``` javascript
this.getByteAt = function(iOffset) {
    var block = getBlockAtOffset(iOffset);
    if(typeof block === "undefined") return 0;
    if( typeof block.data == "string" ) {
```

it's not perfect but it works. it don't give me an error fatal for my website.

i hope this can help you.

(sorry for my english, i'm french).

**Comment by Artlu** [comment]
I also had this issue. If you're loading the file from a different URL, you need to add the following response headers:
Access-Control-Allow-Origin: <origin of the request>
Access-Control-Allow-Headers: If-Modified-Since,Range
Access-Control-Expose-Headers: Accept-Ranges,Content-Encoding,Content-Length,Content-Range

The last header (Access-Control-Expose-Headers) fixed the error "TypeError: block is undefined @ id3/bufferedbinaryajax.js:215"

**Comment by aadsm** [comment]
Of course, I completely forgot about this in CORS.
Thank you very much, I've added a section to the README explaining this.
