### ISSUE TITLE
Weird issue with multiple file upload/ File Reader? tags is always null and all types of scoping/callback hell

### ISSUE THREAD

**Issue by r3wt** [aadsm/JavaScript-ID3-Reader#53]
I was hoping you might be able to shed some insight on whats happening here. I realize this library is very complex and javascript scoping is brutal, but i can't for the life of me figure out why this doesn't work as i expect that it should? could you perhaps help me?

```js
var $files = [];
	
$( 'input[name="audio_files"]' ).on( 'change' , function(e) {
	if ( this.files && this.files.length > 0 ) {
		for( var i=0,file; file = this.files[i]; i++ ){
			var $fileObj = {};
			$fileObj.blob = file;
			ID3.loadTags( $fileObj.blob.name , function() {
				console.log( $fileObj.blob.name ); //its there as expected
				var tags = ID3.getAllTags( $fileObj.blob.name );
				console.log(tags); //its always null
				if(tags != null){
					$fileObj.title     = tags.title;
					$fileObj.artist    = tags.artist;
					$fileObj.featuring = '';
				}else{
					$fileObj.title    =  '';
					$fileObj.artist   =  '';
					$fileObj.featuring = '';
				}
				$files.push($fileObj);
			}($fileObj), {
				dataReader: FileAPIReader($fileObj.blob)
			});
		}
	}
});
```

**Comment by r3wt** [comment]
hello?

**Comment by aadsm** [comment]
Hi, 

You are calling the callback function instead of just passing it to `ID3.loadTags`. It feels like you're doing this to solve the lack of scope creation in JavaScript blocks.

Only function calls can create scope and that happens when you call your inline function, however, by doing this you are running the code that should only be executed when the tags are loaded. Your inline function should instead return another function to pass to `ID3.loadTags`.

Your code is almost there, but you should wrap the processing logic in a function to return and pass to `ID3.loadTags`.
You are also not defining the `$fileObj` as a parameter of the inline function, so `$fileObj` will actually be a reference to the variable of the loop, and not captured in the scope of the inline function.

It would be something like:
```javascript
ID3.loadTags( $fileObj.blob.name , (function($fileObj) {
  return function() {
    var tags = ID3.getAllTags($fileObj.blob.name);
  };
})($fileObj)),
```

Here's how to learn more about scopes in JS: http://robertnyman.com/2008/10/09/explaining-javascript-scope-and-closures/ Search for the section "The Infamous Loop Problem".

Personally I think the cleanest way to solve your problem is to create a new function that processes each file and call that function in the for loop:

```javascript
for( var i=0,file; file = this.files[i]; i++ ) {
   var $fileObj = {};
   $fileObj.blob = file;
   $files.push($fileObj);
   loadFileTags($fileObj);
}

function loadFileTags($fileObj) {
  ID3.loadTags( $fileObj.blob.name , function() {
    var tags = ID3.getAllTags( $fileObj.blob.name );
    ...
  });
}
```

**Comment by r3wt** [comment]
why is it necessary to nest `getAllTags` in the callback of `loadTags`. seems counterintuitive to me.  why can't i just call `getAllTags` on a blob?

**Comment by r3wt** [comment]
Is there some alternative? i need to store the tags in `$fileObj` before pushing that object into the `$files` array.

i don't understand this pattern at all. it's counterintuitive
