### ISSUE TITLE
ID3 Bitrate

### ISSUE THREAD

**Issue by madhurgarg71** [aadsm/JavaScript-ID3-Reader#56]
How to extract the bitrate of the mp3 file ?

**Comment by aadsm** [comment]
This library is only concerned with reading ID3 tags out of audio files, so it can't solve your problem directly.

You need to manually calculate the bitrate, if it's constant I believe it's easy but if it's variable which is probably the most common then it's more complicated.
There is one tag - `ASPI` - that might be useful when calculating Variable Bit Rate. You can find its documentation here http://id3.org/id3v2.4.0-frames under 4.30. However, you would need to rely in its existence since it's not mandatory.
